Add blacklist and list of blacklisted phrases/characters
Superior-Development/IcarusMod pull request #180
Opened 2016-04-13 19:57 UTC by Adaptified

Solves #177

2016-04-13 19:58 UTC, CameronRedmore commented
This seems to be okay, there is no nick blacklist however.

2016-04-13 20:13 UTC, Wild1145 commented
The blacklist should be stored as part of the settings table in mySQL

2016-04-13 20:15 UTC, Adaptified commented
@Wild1145 That would create more data for no reason. The blacklist doesn't disappear on a reload or restart like HashMaps and ArrayLists, this is always there and works just fine, no need to create more work and fix something if it isn't broken.

2016-04-13 20:17 UTC, Wild1145 commented
@Adaptified It does however need to be centrally stored and able to be updated in real time as we need.

2016-04-13 20:43 UTC, Adaptified commented
@Wild1145 You're developers, it's not hard to edit the code. That's why github is here, people suggest something and then it happens. Not everything needs to be SQL.

2016-04-13 20:48 UTC, Wild1145 commented
@Adaptified The entire point of this project is that it is fully SQL based, no configigs and everything is global. I and @CameronRedmore may be Java developers, but @TheCJGCJG is not, neither is Varuct, so if they want to make a change, they have to wait for me or Camzie to be free, make the change, test the change and then push and compile. We then have to take the network offline to update it. Or we just follow the project goals to SQL everything and make one minor change to a table and boom, done.

2016-04-13 21:38 UTC, Adaptified commented
@Wild1145 Done.

2016-04-13 21:43 UTC, CameronRedmore commented
The blacklist this takes is simply a comma delimited list in the format: "Admin, Mod, Super, Senior, Telnet, Developer, Manager, Executive, &k, &o, &n, &m, &1, &0" for example. If this string is entered as the value for a new row in the 'settings' table which is named 'blacklist' all of those terms would be blacklisted.

2016-04-14 12:51 UTC, Wild1145 commented on src/com/superiornetworks/icarus/ICM_SqlHandler.java
> +
This should not be there...

2016-04-14 12:51 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +public class Command_nick {
Formatting Issues

2016-04-14 12:51 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +        try {
Formatting Issues

2016-04-14 12:51 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +            if (args.length < 2) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +            if (args[0].equalsIgnoreCase("set")) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (nick.contains("`") || nick.contains("'")) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (nick.length() > 25) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +            } else {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (!ICM_Rank.isRankOrHigher(sender, ICM_Rank.Rank.SUPER)) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (!ICM_SqlHandler.playerExists(args[0])) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (nick.contains("`") || nick.contains("'")) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (nick.length() > 25) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                    if (args[0].equalsIgnoreCase("blacklist")) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                for (String blacklist : ((String) ICM_SqlHandler.getFromTable("settingName", "blacklist", "string", "settings")).split(", ")) {
Formatting Issues

2016-04-14 12:52 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +                if (p != null) {
Formatting Issues

2016-04-14 12:53 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +        } catch (SQLException ex) {
Formatting Issues

2016-04-14 12:53 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +
This should not be here.

2016-04-14 12:53 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +
This should not be here.

2016-04-14 12:53 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +                for (String blacklist : ((String) ICM_SqlHandler.getFromTable("settingName", "blacklist", "string", "settings")).split(", ")) {
Formatting Issues

2016-04-14 12:53 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +                    if (tag.toLowerCase().contains(blacklist.toLowerCase()) && !ICM_Rank.isRankOrHigher(sender, ICM_Rank.Rank.SUPER)) {
Formatting Issues

2016-04-14 12:54 UTC, Adaptified commented
Holy formatting issues. I am guessing you want the bracket under the statement.

2016-04-14 12:55 UTC, Wild1145 commented
@Adaptified It should be in allman style. Just like TFM.

2016-04-14 13:24 UTC, Adaptified commented
@Wild1145 All done.

2016-10-25 21:35 UTC, Wild1145 reviewed
@CameronRedmore Could you take a look and properly review this when you get a moment please.

2016-11-12 21:22 UTC, Wild1145 requested changes
There are some formatting changes that need to be made. You also need to actually create the blacklist in the database upon plugins startup if it is not already created, as right now it does not do that.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/ICM_SqlHandler.java
> +
This shouldnt be here.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +public class Command_nick
This shouldnt be here.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +            if (args.length < 2)
This shouldnt be here.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_nick.java
> +            catch (SQLException ex)
Formatting appears to be out here.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +
This shouldnt be here.

2016-11-12 21:22 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_tag.java
> +            }
This shouldnt be here.

2017-01-07 21:01 UTC, closed without merging