Implement AdminChat Module and Command
Superior-Development/IcarusMod pull request #182
Opened 2016-04-13 20:51 UTC by Adaptified

Solves #173

2016-04-14 10:37 UTC, Wild1145 commented on src/com/superiornetworks/icarus/modules/AdminChat.java
> +                onlineadmins.sendMessage("§f[§bADMIN§f] §c" + sender.getName() + ICM_Rank.getRank(sender).actag + "§f: §b " + message);
Could you change this to get the senders nickname? I have grown to prefer that to just their username.

2016-04-14 10:38 UTC, Wild1145 commented
This currently is not following the guidelines, it requires formatting changes and shouldn't actually work...

2016-04-14 11:13 UTC, Adaptified commented
@Wild1145 You obviously didn't really test this. I compile and test all my changes/PRs, but I will change the senders nickname.

2016-04-14 12:49 UTC, Wild1145 commented
@Adaptified No, I have not tested it, I can however say with confidence that it will not actually function, the command is not being correctly defined. It *may* compile, but it should not work properly.

2016-04-14 12:54 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_o.java
> +        if (args.length == 0) {
Formatting Issues

2016-04-14 12:54 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_o.java
> +                if (!ICM_SqlHandler.inAC(player.getName())) {
Formatting Issues

2016-04-14 12:54 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_o.java
> +                } else {
Formatting Issues

2016-04-14 12:54 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_o.java
> +        if (args.length >= 1) {
Formatting Issues

2016-04-14 13:32 UTC, Adaptified commented
All done @Wild1145

2016-04-14 18:46 UTC, Wild1145 commented on src/com/superiornetworks/icarus/commands/Command_o.java
> +                catch (SQLException ex)
Formattings out here.

2016-11-12 20:31 UTC, Wild1145 requested changes
Additional changes are required, this will not compile.

2016-11-12 20:32 UTC, Wild1145 requested changes
Please make the required changes.

2016-11-12 20:32 UTC, Wild1145 commented on src/com/superiornetworks/icarus/modules/AdminChat.java
> +                onlineadmins.sendMessage("§f[§bADMIN§f] §c" + ICM_SqlHandler.getNick(sender) + ICM_Rank.getRank(sender).actag + "§f: §b " + message);
This does not work. Please review this.

2016-11-27 13:02 UTC, closed without merging